config/routes.rb
KaisenMurata::Application.routes.draw do
  devise_for :admins

  get "orders/index"

  get "store/index"
  get "store" => "store#index", :as => :store
  get "store/suppliers"
  get "orders/index"
  match "store/checkout", :as => :checkout
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/remove_item_from_cart" => "store#remove_item_from_cart"
  post "store/save_order", :as => :save_order
  resources :shops
  resources :orders
  resources :products

  root :to => "store#index"

end

app/models/shop.rb
class Shop < ActiveRecord::Base
 # validates_presence_of :name, :description, :lines_summary
 # validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i,
 #                     :message => "はGIF,JPG,PNG画像のURLでなければなりません"
 # validates_uniqueness_of :name

 has_many :products
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_filter :authenticate_admin!

  # GET /shops
  # GET /shops.xml
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.xml
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.xml
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.xml
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to(@shop, :notice => 'Shop was successfully created.') }
        format.xml  { render :xml => @shop, :status => :created, :location => @shop }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.xml
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to(@shop, :notice => 'Shop was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.xml
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to(shops_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.haml
= form_for @shop do |f|
  -if @shop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      %ul
        - @shop.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :lines_summary
    = f.text_field :lines_summary
  .actions
    = f.submit 'Save'

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
%h1 Listing shops

%table
  %tr
    %th Name
    %th Description
    %th Image url
    %th Lines summary
    %th
    %th
    %th

  - @shops.each do |shop|
    %tr
      %td= shop.name
      %td= simple_format(shop.description)
      %td= image_tag(shop.image_url)
      %td= shop.lines_summary
      %td= link_to 'Show', shop
      %td= link_to 'Edit', edit_shop_path(shop)
      %td= link_to 'Destroy', shop, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.haml
%h1 New shop

= render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @shop.name
%p
  %b Description:
  = simple_format(@shop.description)
%p
  %b Image url:
  = image_tag(@shop.image_url)
%p
  %b Lines summary:
  = @shop.lines_summary

= link_to 'Edit', edit_shop_path(@shop)
\|
= link_to 'Back', shops_path