config/routes.rb
KaisenMurata::Application.routes.draw do
  devise_for :admins

  get "orders/index"

  get "store/index"
  get "store" => "store#index", :as => :store
  get "store/suppliers"
  get "orders/index"
  match "store/checkout", :as => :checkout
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/remove_item_from_cart" => "store#remove_item_from_cart"
  post "store/save_order", :as => :save_order
  resources :shops
  resources :orders
  resources :products

  root :to => "store#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [["現金","checkout"],["クレジットカード","cc"]]
  has_many :line_items
  accepts_nested_attributes_for :line_items,
    :reject_if => lambda {|a| a.values.all?(&:blank?)},
    :allow_destroy => true

  validates_presence_of :name, :address, :email, :pay_type
  validates_inclusion_of :pay_type, :in => PAYMENT_TYPES.map(&:last)

  def add_line_items_from_cart(cart)
    cart.items.each do |item|
      line_item = LineItem.from_cart_item(item)
      line_items << line_item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @orders = Order.order(:created_at).reverse_order
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes!(params[:order])
      redirect_to orders_path, :notice => "注文情報を更新しました"
    else
      render :action => "edit" 
    end
  end  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  -if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, "氏名"
    = f.text_field :name
  .field
    = f.label :address, "住所"
    = f.text_area :address
  .field
    = f.label :email, "Ｅメール"
    = f.text_field :email
  .field
    = f.label :pay_type, "支払い方法"
    = f.select :pay_type, Order::PAYMENT_TYPES, :prompt => "---"

  %h3 売上明細

  = f.fields_for :line_items do |line_item_form|
    = render :partial => "orders/line_item", :locals => { :f => line_item_form } 

  %p
    = add_child_link "[明細行の追加]", f, :line_items, {:id => "add_new_line_item_link"}, {:partial => 'orders/line_item'}

  .actions
    = f.submit "保存する"

app/views/orders/_line_item.html.haml
.fields
  = f.label :product, "商品"
  = f.collection_select :product_id, Product.all, :id, :name, :include_blank => "---"
  = f.label :quantity, "数量" 
  = f.text_field :quantity, :size => 5

app/views/orders/_order.html.haml
%table
  %tr
    %th 注文ID
    %td= order.id
    %th 注文日時
    %td= order.created_at.strftime("%Y-%m-%d %H:%M")
  %tr
    %th 氏名
    %td= order.name
    %th メールアドレス
    %td= order.email
  %tr
    %th 住所
    %td{:colspan => 3}
      = order.address
  %tr
    %th 支払い方法
    %td{:colspan => 3}
      = order.pay_type
  %tr
    %th 注文明細

    %td
      - order.line_items.map(&:product).map(&:name).each do |item_name|
        = item_name
        %br
    %td.number
      - order.line_items.each do|line_item|
        = number_with_delimiter(line_item.product.price)
        *
        = number_with_delimiter(line_item.quantity)
        %br
    %td.number
      -order.line_items.each do |line_item|
        = number_with_delimiter(line_item.product.price * line_item.quantity)
        %br

%p
  = link_to '編集', edit_order_path(order)

%br

app/views/orders/edit.html.haml
%h2 注文情報の編集

= render 'form'

= link_to '戻る', orders_path

app/views/orders/index.html.haml
%h2 注文一覧

= render :partial => "order", :collection => @orders