config/routes.rb
KaisenMurata::Application.routes.draw do
  devise_for :admins

  get "orders/index"

  get "store/index"
  get "store" => "store#index", :as => :store
  get "store/suppliers"
  get "orders/index"
  match "store/checkout", :as => :checkout
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/remove_item_from_cart" => "store#remove_item_from_cart"
  post "store/save_order", :as => :save_order
  resources :shops
  resources :orders
  resources :products

  root :to => "store#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items

  validates_presence_of :name, :description, :image_url, :shop_id
  validates_numericality_of :price, :shop_id, :greater_than => 0, :only_integer => true
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i,
                      :message => "はGIF,JPG,PNG画像のURLでなければなりません"
  validates_uniqueness_of :name
  
  validate :price_must_be_a_multiple_of_hundreds

  private
  def price_must_be_a_multiple_of_hundreds
    errors.add(:price,"価格の最少単位は100です。") if (price % 100) != 0
  end
  
  scope :for_sale, :order => "created_at DESC"  
  scope :name_like, lambda {|q| {:conditions => ['name like ?', "%#{q}%"]}}
  scope :recent, lambda {|num| {:limit => num, :order => "created_at DESC"}}
  scope :recommended, :conditions => {:recommended => true}
  belongs_to :shop
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_admin!

  # GET /products
  # GET /products.xml
  def index
    @products = Product.recent.all.paginate :page => params[:page], :per_page => 5


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :shop_id
    = f.collection_select :shop_id, Shop.all, :id, :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :recommended
    = f.check_box :recommended
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Name
    %th Shop
    %th Description
    %th Image url
    %th Price
    %th Recommended
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.shop.name
      %td= simple_format(product.description)
      %td= image_tag(product.image_url)
      %td= product.price
      %td= product.recommended
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete

=will_paginate @products
%br
 
=link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Shop:
  = @product.shop.name
%p
  %b Description:
  = simple_format(@product.description)
%p
  %b Image url:
  = image_tag(@product.image_url)
%p
  %b Price:
  = @product.price
%p
  %b Recommended:
  = @product.recommended

= link_to 'Edit', edit_product_path(@product)

= link_to 'Back', products_path