config/routes.rb
KaisenMurata::Application.routes.draw do
  devise_for :admins

  get "orders/index"

  get "store/index"
  get "store" => "store#index", :as => :store
  get "store/suppliers"
  get "orders/index"
  match "store/checkout", :as => :checkout
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/remove_item_from_cart" => "store#remove_item_from_cart"
  post "store/save_order", :as => :save_order
  resources :shops
  resources :orders
  resources :products

  root :to => "store#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KaisenMurata</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/store.html.haml
!!! 5
%html
  %head
    %meta{ "http-qeuiv" => "Content-Type", :content => "text/html: charset=utf-8" }
    %title 買鮮カタログ

    != stylesheet_link_tag 'reset', 'text', '960','store','orders','products'
    != javascript_include_tag :defaults
    != csrf_meta_tag
  %body#store.container_12
    #header.grid_12
      %h1 買鮮カタログ
    .clear
    #columns
      #side.grid_3
        - if @cart
          #cart
            = render :partial => 'cart', :object => @cart
        %ul#nav
          %li
            = link_to "トップ", store_path
          %li
            %a{:href => "#"}ニュース
          %li
            %a{:href => "#"}お問い合わせ
          %li
            %a{:href => "#"}ご利用ガイド
        - if admin_signed_in?
          .title
            管理者メニュー
          %ul#nav
            %li
              = link_to "商品管理", products_path
            %li
              = link_to "店舗管理", shops_path
            %li
              = link_to "注文情報管理", orders_path
            %li
              = link_to "ログアウト", destroy_admin_session_path
      #main.grid_6.suffix_3
        - if flash[:notice]
          .notice= flash[:notice]
        - if flash[:alert]
          .alert= flash[:alert]
        != yield
      .clear
    #footer.grid_12
      %p Copyright (C) 2010 Enishi Tech Inc. All Rights Reserved.
    .clear